server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8190
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/my-market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8191
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/my-market-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8187
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/my-market-auth
            - JwtAuthFilter
jwt:
  secret: aKaztBKD6z66JfEuXzGvPAhuoKHXOhsRdkNKoA3wbPeRCF8Hoy