server:
  port: 8191
  servlet:
    context-path: /my-market-cart
integrations:
  product-service:
    url: http://localhost:8190/my-market-core/
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000

starter-aspect:
  properties:
    enabled: true
    log-level: info