server:
  port: 8190
  servlet:
    context-path: /my-market-core

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:/db/test

integrations:
  cart-service:
    url: http://localhost:8822/my-market-cart/
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000
  user-service:
    url: http://localhost:8822/my-market-auth/
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000