server:
  port: 8190
  servlet:
    context-path: /my-store-core

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_store_core
    username: root
    password: EY9fhJLjXok5TQ%
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mysql:
    console:
      enabled: true
      settings:
        web-allow-others: false

integrations:
  cart-service:
    url: http://localhost:8191/my-store-cart/
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000
  user-service:
    url: http://localhost:8187/my-store-auth/
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000